#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

docker build \
    --build-arg GITHUB_REPO=$GITHUB_REPO \
    --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
    -t $IMAGE_NAME .
